<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $model=$objectManager->create('Ambab\EmiCalc\Model\Grid');
    $datacollection=$model->getCollection();
?>
<div id="information-mpdal" style="padding:20px">
    <table class="table bg-dark text-white">
    <thead>
        <tr>
        <th scope="col">ID</th>
        <th scope="col">Bank Name</th>
        <th scope="col">Emi Plan</th>
        <th scope="col">Rate Of Intrest</th>
        </tr>
    </thead>
    <tbody>
        <?php 
            foreach($datacollection as $data)
            {
        ?>
        <tr>
            <td>
                <?php echo $data->getEntityId(); ?>
            </td>
            <td>
                <?php echo $data->getName(); ?>
            </td>
            <td>
                <?php echo $data->getEmi(); ?>
            </td>
            <td>
                <?php echo $data->getRoi(); ?>
            </td>
            
        </tr>
        <?php
            }
            ?>
    </tbody>
    </table>
</div>


<?php if ($block->canShowBlock()): ?>

    <a id="request-more" href="#">Emi strarts from $100</a>

<?php endif; ?>


<script>
   require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function (
            $,
            modal
        ) {
            var modaloption = {
                type: 'popup',
                title:'Bank Emi Details',
                responsive: true,
                innerScroll: true,
                clickableOverlay: true,
                buttons: []
        };
        var popup = modal(modaloption, $('#information-mpdal'));
        $("#request-more").on('click',function(){ 
            $("#information-mpdal").modal("openModal");
        });
    }
);
</script>






